package springbootproject.springboot.enums;

public enum JobCategoryEnum {
    SALES_MARKETING, SERVICE, HEALTH_CARE, PRODUCTION, //san xuat
    INFORMATION_TECHNOLOGY, ADMINISTRATION, //hanh chinh
    HUMAN_RESOURCES, FINANCIAL_ACCOUNTANT, //KẾ TOÁN / TÀI CHÍNH
    COMMUNICATION_MEDIA,  //TRUYỀN THÔNG / MEDIA
    CONSTRUCTION, //XÂY DỰNG
    TECHNIQUE, EDUCATIONS, SCIENCE, HOTEL_TOURISM, OTHER;


}
